### ISSUE TITLE
Different license for translations

### ISSUE THREAD

**Issue by rob006** [kilowhat/flarum-ext-audit-free#1]
Recently I'm trying to cleanup licenses mess for [translations repository](https://github.com/rob006-software/flarum-translations) and your extension is main fuckup I've made - I copied translations from your repository, even if license strictly forbids this. Could you consider using different license for translation files, so they could be safely used in Weblate and language packs?

**Comment by rob006** [comment]
Related: https://github.com/extiverse/premium-translations/issues/3

**Comment by clarkwinkelmann** [comment]
Sorry I missed this discussion.

I'm not sure how to mark this in the repository but the same conditions that were discussed for premium extensions can be ported to this extension, I have no issue with translators packaging translations for this extension as MIT.

This extension however might create further issues since the translation namespace doesn't adhere to Flarum naming convention :innocent: The same namespace is used for free and pro (and free contains all the translations from pro even if some aren't used)

So technically even if you weren't allowed to copy these translations, Extiverse allows copying those from the pro extension and since they are the same that would work as well.

Do you think I should add a special license file inside of the locales folder?

**Comment by rob006** [comment]
> This extension however might create further issues since the translation namespace doesn't adhere to Flarum naming convention innocent The same namespace is used for free and pro (and free contains all the translations from pro even if some aren't used)

I don't think it would be a problem. Flarum loads files only for enabled extensions based on file name, so there should be no collisions (unless you have them both enabled, but it should not hurt in that case either).

> Do you think I should add a special license file inside of the locales folder?

Adding MIT license file [here](https://github.com/kilowhat/flarum-ext-audit-free/tree/master/resources/locale) would clear any doubts in this matter, so I would prefer to just add it.

**Comment by clarkwinkelmann** [comment]
I have made the changes, the YAML file are now officially MIT licensed.

But it's still perfectly fine by me to reproduce the translation files even without retaining the license.
